const data = {
    products: [
        {   // Variable für Zeit, evtl. start Ende. !! Erst nur festgelegte Zeitrahmen  Startbutton mit Timer 
            name: 'Battlefield 4',
            slug: 'battlefield-4',
            category: 'Shooter',
            image: './images/d1.jpg',
            price: 60,
            countInStock: 3,
            brand: 'DICE',
            rating: 4.5,
            numReviews: 10,
            desription: 'When Battlefield was good',
        },
        {
            name: 'Bloodborne',
            slug: 'bloodborne',
            category: 'RPG',
            image: './images/d2.jpg',
            price: 60,
            countInStock: 3,
            brand: 'FROMSoft',
            rating: 4.5,
            numReviews: 10,
            desription: 'Nice one',
        },
        {
            name: 'Cyberpunk 2077',
            slug: 'cyberpunk-2077',
            category: 'RPG/Shooter',
            image: './images/d3.jpg',
            price: 60,
            countInStock: 3,
            brand: 'CD Project Red',
            rating: 4.5,
            numReviews: 10,
            desription: 'shitty release',
        },
        {
            name: 'Rocket League',
            slug: 'rocket-leauge',
            category: 'Arcade',
            image: './images/d4.jpg',
            price: 60,
            countInStock: 3,
            brand: 'Psyonix',
            rating: 4.5,
            numReviews: 10,
            desription: 'Easy to learn, hard to master',
        },
        {
            name: 'Skyrim',
            slug: 'tes-skyrim',
            category: 'RPG',
            image: './images/d5.jpg',
            price: 60,
            countInStock: 3,
            brand: 'Bethesda',
            rating: 4.5,
            numReviews: 10,
            desription: 'FUS RO DAH',
        },
        {
            name: 'The Witcher 3',
            slug: 'the-witcher-3',
            category: 'RPG',
            image: './images/d6.jpg',
            price: 60,
            countInStock: 3,
            brand: 'CD Project Red',
            rating: 4.5,
            numReviews: 10,
            desription: 'GOAT',
        },
    ],
};

export default data;